name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install IBM Cloud CLI and plugins
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install code-engine
          ibmcloud plugin install event-streams  # Install Event Streams plugin
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r au-syd
          docker login -u iamapikey -p ${{ secrets.IBM_CLOUD_API_KEY }} au.icr.io
          ibmcloud target -g Default
          ibmcloud ce project select -n my-kafka-project
          
      - name: Initialize Event Streams plugin
        run: |
          ibmcloud es init  # Initialize the Event Streams plugin and select your instance

      # Create Applications with Dummy Images (Temporary)
      # - name: Create Applications with Dummy Images (Temporary)
      #   run: |
      #     # Create User Service with a dummy image
      #     ibmcloud ce application create --name user-service \
      #       --image nginx:alpine \
      #       --port 80 \
      #       --registry-secret icr-secret

      #     # Create Order Service with a dummy image
      #     ibmcloud ce application create --name order-service \
      #       --image nginx:alpine \
      #       --port 80 \
      #       --registry-secret icr-secret

      # Bind Event Streams Service
      - name: Bind Event Streams Service
        run: |
          # For User Service
          ibmcloud ce application bind --name user-service \
            --service-instance my-event-streams \
            --prefix EVENT_STREAMS

          # For Order Service
          ibmcloud ce application bind --name order-service \
            --service-instance my-event-streams \
            --prefix EVENT_STREAMS

      - name: Build & Push Docker Image (User Service)
        run: |
          docker build -t au.icr.io/mycodeengine/user-service:latest ./user-service
          docker push au.icr.io/mycodeengine/user-service:latest

      - name: Deploy User Service to Code Engine
        run: |
          ibmcloud ce application update --name user-service --image au.icr.io/mycodeengine/user-service:latest

      - name: Build & Push Docker Image (Order Service)
        run: |
          docker build -t au.icr.io/mycodeengine/order-service:latest ./order-service
          docker push au.icr.io/mycodeengine/order-service:latest

      - name: Deploy Order Service to Code Engine
        run: |
          ibmcloud ce application update --name order-service --image au.icr.io/mycodeengine/order-service:latest
